[build]
  command = "npm run web-build" # Comando per costruire la versione web di Expo
  publish = "dist"         # Directory dove Expo salva i file della build web

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
